services:
  osrm:
    image: osrm/osrm-backend
    command: osrm-routed /data/northern-zone-latest.osrm
    volumes:
      - ./data:/data
    ports:
      - "5000:5000"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - AQI_TOKEN=${AQI_TOKEN}

  aqi-fetcher:
    build: ./backend
    command: ["node", "scripts/fetch-aqi.js"]
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - AQI_TOKEN=${AQI_TOKEN}

  postgis:
    build:
      context: .
      dockerfile: Dockerfile.postgis
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ecoroutes
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgis-data:/var/lib/postgresql/data
      - ./data:/data

volumes:
  postgis-data:
