FROM postgis/postgis:16-3.4

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install -y --no-install-recommends gdal-bin curl && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
